#端口
server:
  port: 8888

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/trial?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  #redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址,端口
    host: 121.199.164.16
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait:
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 1000ms
# mybitis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #开启sql打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#log
logging:
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
    # 默认日志文件名
#    file: log
    # 默认日志路径
#     path: ./log
#     logback.xml路径，默认为classpath:logback.xml
#     config: ./logback.xml

